name:                nyf
version:             0.1.3.0
github:              "laluxx/nyf"
license:             MIT
author:              "Laluxx"
maintainer:          "lorenzoaddamo10@gmail.com"
copyright:           "2026 Laluxx"
extra-source-files:
- README.org
- LICENSE
description:         Formatter for the Nytrix programming language

data-files:
- tests/**
- etc/**/*

dependencies:
- base >= 4.7 && < 5
- text
- yaml
- time
- filepath
- directory
- megaparsec
- prettyprinter
- parser-combinators
- aeson
- bytestring
- process
- bytestring
- aeson-pretty
- fsnotify
- warp
- wai
- wai-websockets
- websockets
- http-types
- containers

nytryx-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - AST
  - Cli
  - Colors
  - Debug
  - Docs
  - FormatConfig
  - Formatter
  - HelpSystem
  - Parser
  - Templates
  - Test
  - Ops.AstOps
  - Ops.ConfigOps
  - Ops.DocsOps
  - Ops.FormatOps
  - Ops.LintOps
  - Ops.ProjectOps
  - Ops.TestOps

executables:
  nyf:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nyf
